site_name: Linguistics Handbook
theme:
  name: material
  palette:
    primary: deep orange
  features:
    - navigation.expand # Makes sure that pages are not collapsed in sidebar on left
    - navigation.top # Back to top button
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde # Enables use of tilde for subscript
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
features:
  - navigation.tracking
  - navigation.instant
  - navigation.tabs
  # - navigation.tabs.sticky
plugins:
  - search
  - print-site
