site_name: Linguistics Handbook
theme:
  name: material
  palette:
    primary: deep orange
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
features:
  - navigation.tracking
  - navigation.instant
  - navigation.tabs
  # - navigation.tabs.sticky
